### ISSUE TITLE
Add syntax validation for ExpressionAttributeNames

### ISSUE THREAD

**Issue by sofianavasr** [truora/minidyn#2]
An expression attribute name must begin with a pound sign (#), and be followed by one or more alphanumeric characters.

**Comment by kuadrosx** [comment]
also review if it is not a reserved word

**Comment by StephanGuingor** [comment]
> also review if it is not a reserved word

but thats for attribute names right? Should this issue validate ExpressionAttributeNames and AttributeNames?
